# -*- coding: utf-8 -*-
"""Account_Enrichment_App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13AjSR1ivRlZpmdKwenZjJZBDENkYOIIc
"""

!pip install streamlit pyngrok beautifulsoup4 requests pandas openpyxl google-search-results serpapi

!streamlit run app.py &>/content/logs.txt &

app_code = '''

import streamlit as st
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
from serpapi import GoogleSearch
from urllib.parse import urlparse

# =====================================================
# SERPAPI KEY
# =====================================================
SERPAPI_KEY = "Enter API Key"

# =====================================================
# PAGE TITLE
# =====================================================
st.title("Account Enrichment App")

st.write("Enter company names (one company per line)")

# =====================================================
# USER INPUT
# =====================================================
companies = st.text_area(
    "Company Names",
    height=200,
    placeholder="HubSpot"
)

# =====================================================
# BAD DOMAINS
# =====================================================
BAD_DOMAINS = [

    "instagram.com",

    "facebook.com",

    "twitter.com",

    "youtube.com",

    "wikipedia.org",

    "linkedin.com/pulse",

    "linkedin.com/posts",

    "g2.com",

    "capterra.com",

    "softwareadvice.com"
]

# =====================================================
# GOOD NEWS DOMAINS
# =====================================================
GOOD_NEWS_DOMAINS = [

    "techcrunch.com",

    "forbes.com",

    "reuters.com",

    "venturebeat.com",

    "businesswire.com",

    "crunchbase.com",

    "zdnet.com",

    "theverge.com"
]

# =====================================================
# CLEAN DOMAIN
# =====================================================
def clean_domain(url):

    try:

        parsed = urlparse(url)

        domain = parsed.netloc.lower()

        domain = domain.replace("www.", "")

        parts = domain.split(".")

        if len(parts) >= 2:

            root_domain = (
                parts[-2] + "." + parts[-1]
            )

            return "https://www." + root_domain

    except:
        return ""

    return ""

# =====================================================
# VALID WEBSITE
# =====================================================
def is_valid_website(url):

    for bad in BAD_DOMAINS:

        if bad in url.lower():
            return False

    return True

# =====================================================
# EMAIL EXTRACTION
# =====================================================
def extract_emails(text):

    emails = re.findall(

        r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}",

        text
    )

    cleaned = []

    for email in emails:

        email = email.lower()

        if email not in cleaned:

            cleaned.append(email)

    return cleaned[:2]

# =====================================================
# PHONE EXTRACTION
# =====================================================
def extract_phones(text):

    phones = re.findall(

        r"(?:\+\d{1,3}[- ]?)?\(?\d{2,4}\)?[- ]?\d{3,4}[- ]?\d{4}",

        text
    )

    cleaned = []

    for phone in phones:

        phone = phone.strip()

        if len(phone) >= 10:

            if phone not in cleaned:

                cleaned.append(phone)

    return cleaned[:2]

# =====================================================
# EMPLOYEE SIZE
# =====================================================
def extract_employee_size(text):

    patterns = [

        r'(\\d{1,3}[,\\d]*)\\+?\\s+employees',

        r'(\\d{1,3}[,\\d]*)\\s+employee',

        r'(\\d{1,3}[,\\d]*)\\+?\\s+people'
    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            text.lower()
        )

        if match:

            return match.group(1)

    return ""

# =====================================================
# INDUSTRY EXTRACTION
# =====================================================
def extract_industry(text):

    industries = [

        "Software",

        "CRM",

        "SaaS",

        "Technology",

        "Cloud",

        "Marketing",

        "Finance",

        "Healthcare",

        "Manufacturing",

        "Logistics"
    ]

    for industry in industries:

        if industry.lower() in text.lower():

            return industry

    return ""

# =====================================================
# LOCATION EXTRACTION
# =====================================================
def extract_location(text):

    states = [

        "California",

        "Texas",

        "Massachusetts",

        "Florida",

        "Washington",

        "New York"
    ]

    countries = [

        "United States",

        "USA",

        "India",

        "Canada",

        "Australia",

        "UK"
    ]

    state = ""
    country = ""
    zipcode = ""

    for s in states:

        if s.lower() in text.lower():

            state = s

    for c in countries:

        if c.lower() in text.lower():

            country = c

    zip_match = re.search(
        r'\\b\\d{5}(?:-\\d{4})?\\b',
        text
    )

    if zip_match:

        zipcode = zip_match.group()

    return state, country, zipcode

# =====================================================
# BUTTON
# =====================================================
if st.button("Enrich Companies"):

    final_results = []

    company_list = companies.split("\\n")

    for company in company_list:

        company = company.strip()

        if company == "":
            continue

        st.write(f"Researching: {company}")

        # =====================================================
        # EMPTY PROFILE
        # =====================================================
        profile = {

            "Company Name": company,

            "Official Website": "",

            "LinkedIn": "",

            "Industry": "",

            "Employee Size": "",

            "HQ State": "",

            "HQ Country": "",

            "HQ Zipcode": "",

            "Phone Number 1": "",

            "Phone Number 2": "",

            "Email 1": "",

            "Email 2": "",

            "Recent News 1": "",

            "Recent News 2": "",

            "Source": ""
        }

        all_emails = []
        all_phones = []
        sources = []

        # =====================================================
        # SEARCH QUERIES
        # =====================================================
        queries = [

            company + " official website",

            company + " linkedin company",

            company + " employee size",

            company + " headquarters",

            company + " industry",

            company + " support email",

            company + " contact phone",

            company + " funding OR acquisition OR AI launch"
        ]

        for query in queries:

            try:

                engine_type = "google"

                if (
                    "funding" in query.lower()
                    or "acquisition" in query.lower()
                    or "launch" in query.lower()
                ):

                    engine_type = "google_news"

                params = {

                    "engine": engine_type,

                    "q": query,

                    "api_key": "Enter API key",

                    "num": 5
                }

                search = GoogleSearch(params)

                results = search.get_dict()

                organic_results = results.get(
                    "organic_results",
                    []
                )

                if engine_type == "google_news":

                    organic_results = results.get(
                        "news_results",
                        []
                    )

                for result in organic_results:

                    link = result.get("link", "")

                    snippet = result.get(
                        "snippet",
                        ""
                    )

                    title = result.get(
                        "title",
                        ""
                    )

                    if link == "":
                        continue

                    # =====================================================
                    # FILTER BAD DOMAINS
                    # =====================================================
                    if not is_valid_website(link):
                        continue

                    # =====================================================
                    # OFFICIAL WEBSITE
                    # =====================================================
                    if (
                        profile["Official Website"] == ""
                    ):

                        cleaned_url = clean_domain(
                            link
                        )

                        domain = cleaned_url.lower()

                        company_clean = (
                            company.lower()
                            .replace(" ", "")
                            .replace(".", "")
                        )

                        if company_clean in domain:

                            profile[
                                "Official Website"
                            ] = cleaned_url

                    # =====================================================
                    # LINKEDIN
                    # =====================================================
                    if (
                        "linkedin.com/company"
                        in link.lower()
                    ):

                        profile["LinkedIn"] = link

                    # =====================================================
                    # INDUSTRY
                    # =====================================================
                    if (
                        profile["Industry"] == ""
                    ):

                        industry = extract_industry(
                            snippet
                        )

                        if industry != "":

                            profile[
                                "Industry"
                            ] = industry

                    # =====================================================
                    # EMPLOYEE SIZE
                    # =====================================================
                    if (
                        profile["Employee Size"] == ""
                    ):

                        emp_size = (
                            extract_employee_size(
                                snippet
                            )
                        )

                        if emp_size != "":

                            profile[
                                "Employee Size"
                            ] = emp_size

                    # =====================================================
                    # LOCATION
                    # =====================================================
                    state, country, zipcode = (
                        extract_location(snippet)
                    )

                    if (
                        profile["HQ State"] == ""
                        and state != ""
                    ):

                        profile["HQ State"] = state

                    if (
                        profile["HQ Country"] == ""
                        and country != ""
                    ):

                        profile["HQ Country"] = country

                    if (
                        profile["HQ Zipcode"] == ""
                        and zipcode != ""
                    ):

                        profile["HQ Zipcode"] = zipcode

                    # =====================================================
                    # RECENT NEWS
                    # =====================================================
                    if engine_type == "google_news":

                        if any(
                            good in link.lower()
                            for good in GOOD_NEWS_DOMAINS
                        ):

                            if (
                                profile["Recent News 1"]
                                == ""
                            ):

                                profile[
                                    "Recent News 1"
                                ] = link

                            elif (
                                profile["Recent News 2"]
                                == ""
                            ):

                                profile[
                                    "Recent News 2"
                                ] = link

                    # =====================================================
                    # SOURCE
                    # =====================================================
                    if "Google" not in sources:

                        sources.append("Google")

                    # =====================================================
                    # OPEN PAGE
                    # =====================================================
                    try:

                        headers = {

                            "User-Agent":
                            "Mozilla/5.0"
                        }

                        response = requests.get(

                            link,

                            headers=headers,

                            timeout=10
                        )

                        soup = BeautifulSoup(

                            response.text,

                            "html.parser"
                        )

                        page_text = soup.get_text(

                            separator=" ",

                            strip=True
                        )

                        # =====================================================
                        # EMAILS
                        # =====================================================
                        emails = extract_emails(
                            page_text
                        )

                        for email in emails:

                            if (
                                email
                                not in all_emails
                            ):

                                all_emails.append(
                                    email
                                )

                        # =====================================================
                        # PHONES
                        # =====================================================
                        phones = extract_phones(
                            page_text
                        )

                        for phone in phones:

                            if (
                                phone
                                not in all_phones
                            ):

                                all_phones.append(
                                    phone
                                )

                    except:
                        pass

            except:
                pass

        # =====================================================
        # EMAILS
        # =====================================================
        if len(all_emails) > 0:

            profile["Email 1"] = all_emails[0]

        if len(all_emails) > 1:

            profile["Email 2"] = all_emails[1]

        # =====================================================
        # PHONES
        # =====================================================
        if len(all_phones) > 0:

            profile["Phone Number 1"] = all_phones[0]

        if len(all_phones) > 1:

            profile["Phone Number 2"] = all_phones[1]

        # =====================================================
        # SOURCE
        # =====================================================
        profile["Source"] = ", ".join(sources)

        # =====================================================
        # SAVE
        # =====================================================
        final_results.append(profile)

    # =====================================================
    # DATAFRAME
    # =====================================================
    df = pd.DataFrame(final_results)

    st.dataframe(df)

    # =====================================================
    # EXPORT EXCEL
    # =====================================================
    excel_file = "account_enrichment_app.xlsx"

    df.to_excel(
        excel_file,
        index=False
    )

    with open(excel_file, "rb") as file:

        st.download_button(

            label="Download Excel",

            data=file,

            file_name="account_enrichment_app.xlsx",

            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )

'''

with open("app.py", "w") as f:

    f.write(app_code)

print("Updated account_enrichment_app created!")

from pyngrok import ngrok

# Replace 'YOUR_AUTHTOKEN' with your actual ngrok authtoken
# You can get your authtoken from the ngrok dashboard: https://dashboard.ngrok.com/get-started/your-authtoken
ngrok.set_auth_token("Enetr API Key")

public_url = ngrok.connect(8501)

print(public_url)